name: Keycloak Scalability Benchmark on Schedule

on:
  # This scheduled run is now disabled, as it has been superseded by rosa-scaling-benchmark.yml
  # This workflow should eventually be removed.
  workflow_dispatch:

jobs:

  checkout:
    name: ROSA Scheduled Create cluster
    runs-on: ubuntu-latest
    steps:
      - name: Run ClientSecret scalability benchmark
        run: |
          gh workflow run -R keycloak/keycloak-benchmark keycloak-scalability-benchmark.yml \
            -f "scenarioName=authentication.ClientSecret"
        if: github.event_name != 'schedule' || github.repository == 'keycloak/keycloak-benchmark'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run AuthorizationCode scalability scenario
        run: |
          gh workflow run -R keycloak/keycloak-benchmark keycloak-scalability-benchmark.yml \
            -f "scenarioName=authentication.AuthorizationCode" \
            -f "numberOfEntitiesInRealm=100000"
        if: github.event_name != 'schedule' || github.repository == 'keycloak/keycloak-benchmark'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
