name: Nightly Release

on:
  push:
    branches:
      - main
      - is-187-revise-docs-and-nightly-build

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Cache Maven Wrapper
        uses: actions/cache@v3
        with:
          path: |
            .mvn/wrapper/maven-wrapper.jar
          key: ${{ runner.os }}-maven-wrapper-${{ hashFiles('**/maven-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-maven-wrapper-
      - name: Build
        run:
          mvn clean install
      - name: Delete existing release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ( gh release view nightly --repo ${{ github.repository_owner }}/${{ github.event.repository.name }} &> /dev/null ); then
            gh release delete nightly --repo ${{ github.repository_owner }}/${{ github.event.repository.name }} --yes
          fi
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          release_name: Keycloak Benchmark Nightly
          draft: false
          prerelease: true
          body: |
            Latest version built from the `main` branch.
      - name: Publish dataset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dataset/target/keycloak-benchmark-dataset-${{ steps.get_version.outputs.VERSION }}.jar
          asset_name: keycloak-benchmark-dataset-${{ steps.get_version.outputs.VERSION }}.jar
          asset_content_type: application/gzip
      - name: Publish kcb ZIP
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./benchmark/target/keycloak-benchmark-${{ steps.get_version.outputs.VERSION }}.zip
          asset_name: kcb-${{ steps.get_version.outputs.VERSION }}.zip
          asset_content_type: application/gzip
      - name: Publish kcb TAR
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./benchmark/target/keycloak-benchmark-${{ steps.get_version.outputs.VERSION }}.tar.gz
          asset_name: kcb-${{ steps.get_version.outputs.VERSION }}.tar.gz
          asset_content_type: application/gzip
