name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Maven packages
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
          key: cache-1-${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: cache-1-${{ runner.os }}-m2
      - name: Build
        run:
          mvn clean install
      - name: Upload dataset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dataset/target/*.jar
          asset_name: keycloak-benchmark-dataset-$tag.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"
      - name: Upload kcb
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: gatling/target/target/*.tar.gz
          asset_name: kcb-$tag.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"